Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob  
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://tcs-edureka-data-engineering/code_pipeline_folder/script/aws_glue_script_amazon_json_transformation.py
      DefaultArguments:
        "--TempDir": "s3://tcs-edureka-data-engineering/code_pipeline_folder/temp/"
      GlueVersion: "3.0"
      WorkerType: G.1X
      NumberOfWorkers: 2


  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-MyRoleForGlue"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole